package com.etoak.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.18
 * 2020-06-01T11:16:07.803+08:00
 * Generated source version: 3.1.18
 * 
 */
@WebService(targetNamespace = "http://service.etoak.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getById", targetNamespace = "http://service.etoak.com/", className = "com.etoak.service.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://service.etoak.com/", className = "com.etoak.service.GetByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.etoak.service.User getById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
